name: 'Test'

on:
  pull_request:
    types: [opened]
    branches:
    - 'master'

jobs:
  test:
    name: Running Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checking out repo'
      uses: actions/checkout@v2
        
    - name: 'Running Tests'
      run: swift test --enable-test-discovery


